# Generated by Django 5.0.7 on 2024-10-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('politics', 'Politics'), ('science', 'Science')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.article')),
            ],
        ),
    ]
