# Generated by Django 5.0.8 on 2024-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
